### PR TITLE
fix: merge Middleware and API route response cookies

### LINKED ISSUE #1797: Middleware should merge API route response cookies
Currently, calling `res.cookies.set` in middleware replaces any cookies set by an API route. Instead they should be merged. 

e2e test: `skip-trailing-slash-redirect`

### PR DESCRIPTION
**Pull request by taty2010**
### Summary
When adding the Middleware headers to the response we ended up overriding the cookies set by the API route and returning only the cookies set within middleware. This fix ensures that the cookies set within the Middleware and API route are merged, by using 'append' instead of 'set', and that they are in the correct order. 

### Relevant links (GitHub issues, Notion docs, etc.) or a picture of cute animal
Fixes #1797 
### Standard checks:

- [ ] Check the Deploy Preview's Demo site for your PR's functionality
- [ ] Add docs when necessary

---

🧪 Once merged, make sure to update the version if needed and that it was published correctly.

### CODE REVIEW

File: packages/runtime/src/templates/edge-shared/utils.ts [hunk 1]
```diff
@@ -31,8 +31,13 @@ export const addMiddlewareHeaders = async (
   // We need to await the response to get the origin headers, then we can add the ones from middleware.
   const res = await originResponse
   const response = new Response(res.body, res)
+  let originCookies = response.headers.get('set-cookie')
```
Comment (ericapisani) [inline packages/runtime/src/templates/edge-shared/utils.ts:34]: Because `originCookies` isn't being modified after being set, this can instead be written as

```suggestion
  const originCookies = response.headers.get('set-cookie')
```

**Review by ericapisani — CHANGES_REQUESTED** [review]
One small thing, but otherwise looks great!

File: packages/runtime/src/templates/edge-shared/utils.ts [hunk 2]
```diff
@@ -31,8 +31,13 @@ export const addMiddlewareHeaders = async (
   // We need to await the response to get the origin headers, then we can add the ones from middleware.
   const res = await originResponse
   const response = new Response(res.body, res)
+  const originCookies = response.headers.get('set-cookie')
   middlewareResponse.headers.forEach((value, key) => {
     response.headers.set(key, value)
+    // Append origin cookies after middleware cookies
+    if (key == 'set-cookie' && originCookies) {
```
Comment (ascorbic) [inline packages/runtime/src/templates/edge-shared/utils.ts:38]:
```suggestion
    if (key === 'set-cookie' && originCookies) {
```
We should (almost) always use strict comparison

**Review by ascorbic — APPROVED** [review]
Great stuff!

**Review by ericapisani — APPROVED** [review]
