### PR TITLE
fix: correctly match params in edge runtime

### LINKED ISSUE #1890: [Bug]: edge rendered dynamic routes do not correctly parse slugs into params
### Summary

Dynamic routes rendered on the edge with `runtime: 'experimental-edge'` do not correctly parse the slug into the page parameters.

This is demonstrated by the failing e2e test: `edge-render-getserversideprops`

### Steps to reproduce

1. Clone the repro and deploy to Netlify
2. Visit `/123?hello=world`

Expected: `{"url":"/123?hello=world","query": {"hello":"world" ,"id":"123"},"params": {"id":"123"},"now": 1673955487763}`

Actual: `{"url":"/123?hello=world","query": {"hello":"world"},"now": 1673955487763}`

### A link to a reproduction repository

https://github.com/orinokai/test-next-edge-slug

### Next Runtime version

4.30.0

### More information about your build

- [ ] I am building using the CLI
- [ ] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

None

### Your netlify.toml file

_No response_

### Your public/_redirects file

_No response_

### Your `next.config.js` file

_No response_

### Builds logs (or link to your logs)

_No response_

### Function logs

_No response_

### .next JSON files

_No response_

### PR DESCRIPTION
**Pull request by ascorbic**
### Summary

Next.js was not populating the params from dynamic edge runtime pages. This PR fixes that by populating the `x-matched-path` header, which along with setting minimal mode, makes Next.js parse the params as if we're on a certain triangle-shaped host. This includes correctly populating the params.

Fixes #1890

### Test plan

1. Visit `/edge/123?hello=world` in the default demo
2. Check that query is `{ id: '123', hello: 'world' }` and params is `{ id: '123' }`

### Relevant links (GitHub issues, Notion docs, etc.) or a picture of cute animal
pão em forma de capivara

### Standard checks:

- [ ] Check the Deploy Preview's Demo site for your PR's functionality
- [ ] Add docs when necessary

---

🧪 Once merged, make sure to update the version if needed and that it was published correctly.

### CODE REVIEW

**Review by orinokai — APPROVED** [review]
Nice one, looks/works great 🚢

File: test/e2e/next-test-lib/next-test-utils.js [hunk 1]
```diff
@@ -128,7 +128,9 @@ export function renderViaHTTP(appPort, pathname, query, opts) {
 export async function fetchViaHTTP(appPort, pathname, query = undefined, opts = undefined, useUndici = false) {
   const url = `${pathname}${typeof query === 'string' ? query : query ? `?${qs.stringify(query)}` : ''}`
   const fetch = useUndici ? undiciFetch : nodeFetch
-  return fetch(getFullUrl(appPort, url), opts)
+  const fullUrl = getFullUrl(appPort, url)
+  console.log(`Fetching url: ${fullUrl}`)
```
Comment (nickytonline) [inline test/e2e/next-test-lib/next-test-utils.js:132]: Was this for debugging purposes only?

File: test/e2e/modified-tests/edge-render-getserversideprops/index.test.ts [hunk 2]
```diff
@@ -36,7 +37,7 @@ describe('edge-render-getserversideprops', () => {
     expect(props.url).toBe('/123?hello=world')
   })
 
-  it('should have correct query/params on rewrite', async () => {
+  usuallySkip('should have correct query/params on rewrite', async () => {
```
Comment (nickytonline) [inline test/e2e/modified-tests/edge-render-getserversideprops/index.test.ts:40]: Are all the `usuallySkip` too flaky at the moment? If so, can we create an issue to deflakify?

File: packages/runtime/src/helpers/edge.ts [hunk 3]
```diff
@@ -470,6 +472,10 @@ export const writeEdgeFunctions = async ({
         ]),
       )
 
+      const dataRoutesMap = new Map(
```
Comment (nickytonline) [inline packages/runtime/src/helpers/edge.ts:475]: Can you add some comments for the changes in this file? It looks like we create a map of data routes (if data routes exist) and set the values to the regex corresponding to the data route, and later on below, it looks like the edge function gets mapped to the specific data route?

And for the cache part below, that's for edge caching but only if using the app dir feature?

File: packages/runtime/src/templates/edge/function-runtime.ts [hunk 4]
```diff
@@ -11,6 +11,7 @@ const handler = async (req: Request, context: Context) => {
     return redirect
   }
   const request = buildNextRequest(req, context, nextConfig)
+  request.headers['x-matched-path'] ||= edgeFunctionDefinition.page
```
Comment (nickytonline) [inline packages/runtime/src/templates/edge/function-runtime.ts:14]: Here, the `edgeFunctionDefinition.page` will populate the `x-matched-path` header only if it's not set, but from the issue this fixes, isn't the x-matched-path always not set, or is this because it's only when running on the edge in minimal mode?

File: test/e2e/next-test-lib/next-test-utils.js (hunk 1 above)
Comment (ascorbic) [reply test/e2e/next-test-lib/next-test-utils.js:132]: No, I've added them to the test script because it makes it a lot easier to debug failures if you can see the actual URL that was loaded

File: packages/runtime/src/helpers/edge.ts (hunk 3 above)
Comment (ascorbic) [reply packages/runtime/src/helpers/edge.ts:475]: Sure thing. I'll add a comment. Re the caching, it's the same as the one right above: only enabled for appDir because it's experimental

File: packages/runtime/src/templates/edge/function-runtime.ts (hunk 4 above)
Comment (ascorbic) [reply packages/runtime/src/templates/edge/function-runtime.ts:14]: This is for forward-compatibility: edge router will pre-populate this value, so we'll keep that value if it's set

File: test/e2e/modified-tests/edge-render-getserversideprops/index.test.ts (hunk 2 above)
Comment (ascorbic) [reply test/e2e/modified-tests/edge-render-getserversideprops/index.test.ts:40]: No, they're ones that haven't been implemented yet. This whole suite was previously disabled, but now the params work then we can enable it except for these two ones that need edge router. `usuallySkip` is just a way of having `it.skip` that can be enabled with an env var

**Review by nickytonline — APPROVED** [review]
Thanks for adding the comments @ascorbic! I tested this out per the test steps and works like a charm! 🚢 

image
