### PR TITLE
fix: now data routes for dynamic routes filter even when null when creating the RSC data router

### LINKED ISSUE #1940: Bug: `appDir` applications can have `dataRoute: null`
When you run `next build` on https://github.com/redmonkez12/interactive-rating-component/tree/079f65a9b1d84efe2c1032dc01c022b46a7c0fb5, then `prerender-manifest.json` will contain

```json
"/api/hello": {
    "initialHeaders": { "content-type": "text/plain;charset=UTF-8" },
    "initialRevalidateSeconds": false,
    "srcRoute": "/api/hello",
    "dataRoute": null
  }
```

Our runtime currently can't handle that, and will throw an error here, because `dataRoute is null`:

https://github.com/netlify/next-runtime/blob/72ab895be865402fa0d92431f293129c70ae6c8b/packages/runtime/src/templates/edge-shared/rsc-data.ts#L38

To fix that, we should update the Next.js version that this repo is pulling TS types from, and fix all places where the types now fail.

### PR DESCRIPTION
**Pull request by nickytonline**
### Summary

There was a TypeScript error that was not picked up as we copy them for the build. I've added some tests to cover this like we did in #2018.

Closes #1940

### Test plan

1. Ensure the deploy previews are green.
2. There are tests that cover this fix.

### Standard checks:

- [x] Check the Deploy Preview's Demo site for your PR's functionality
- [ ] Add docs when necessary

---

🧪 Once merged, make sure to update the version if needed and that it was published correctly.

someone petting an alapaca

### CODE REVIEW

File: packages/runtime/src/templates/edge-shared/rsc-data.ts [hunk 1]
```diff
@@ -44,7 +44,7 @@ export const getRscDataRouter = ({ routes: staticRoutes, dynamicRoutes }: Preren
   )
 
   const dynamicRouteMatcher = Object.values(dynamicRoutes)
-    .filter(({ dataRoute }) => dataRoute.endsWith('.rsc'))
+    .filter(({ dataRoute }) => dataRoute?.endsWith('.rsc'))
```
Comment (nickytonline) [inline packages/runtime/src/templates/edge-shared/rsc-data.ts:47]: As mentioned in the description of the PR this wasn't being caught during compilation of the Next runtime as this file is copied.

**Review by sarahetter — APPROVED** [review]
